# Generated by Django 3.2.5 on 2021-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210802_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
