# Generated by Django 3.2.5 on 2021-08-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_student_is_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='download_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_name', models.CharField(max_length=200)),
                ('download_url', models.URLField()),
            ],
        ),
    ]
