# Generated by Django 3.2.5 on 2021-08-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_download_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='download_links',
            new_name='download_link',
        ),
    ]
