# Generated by Django 3.2.5 on 2021-08-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
