# Generated by Django 3.2.5 on 2021-08-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title of todo'),
        ),
    ]
