# Generated by Django 3.2.5 on 2021-08-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='todo_backlog',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
