# Generated by Django 3.2.5 on 2021-08-04 21:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_student_todo_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='todo_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
