# Generated by Django 3.2.5 on 2021-08-05 00:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20210804_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_link',
            name='challenges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='download_link',
            name='checkpoint',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='download_link',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
