# Generated by Django 3.2.5 on 2021-08-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_auto_20210804_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cash',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='xp',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
