# Generated by Django 3.2.5 on 2021-08-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20210804_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
