# Generated by Django 3.2.5 on 2021-08-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_auto_20210805_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='todo_backlog',
            new_name='backlog',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='todo_doing',
            new_name='doing',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='todo_done',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='todo_todo',
            new_name='to_do',
        ),
    ]
