# Generated by Django 3.2.5 on 2021-08-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_auto_20210805_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pk_test',
            fields=[
                ('pk_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pk_add', models.CharField(max_length=25)),
            ],
        ),
    ]
