# Generated by Django 3.2.5 on 2021-08-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_pk_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pk_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_add', models.CharField(max_length=25)),
                ('pk_relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.pk_test')),
            ],
        ),
    ]
