# Generated by Django 3.2.5 on 2021-08-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_pk_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_link',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='download_link',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
