# Generated by Django 3.2.5 on 2021-08-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_auto_20210805_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download_link',
            old_name='download_name',
            new_name='download_title',
        ),
    ]
