# Generated by Django 3.2.5 on 2021-08-06 03:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0030_rename_download_name_download_link_download_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download_link',
            old_name='points',
            new_name='download_points',
        ),
        migrations.AddField(
            model_name='download_link',
            name='challenge_points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
