# Generated by Django 3.2.5 on 2021-08-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_student_todo_backlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='todo_backlog',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
